name: "dbt_kustomer"
version: "0.1.0"
config-version: 2
require-dbt-version: ">=1.3.0"
profile: "dbt_kustomer"

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Where the tap data is expected to be landed
vars:
  kustomer_database: kustomer
  kustomer_schema: tap_kustomer

# Model configuration
models:
  dbt_kustomer:
    marts:
      +schema: kustomer
      +materialized: table
    staging:
      +schema: stg_kustomer
      +materialized: view
