name: "dbt_kustomer"
version: "0.1.0"
config-version: 2

profile: "dbt_kustomer"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_kustomer:
    staging:
      +materialized: table
