name: "dbt_kustomer_integration_tests"
version: "1.0"
config-version: 2

profile: "integration_tests"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  kustomer_schema: integration_tests_{{ env_var('GITHUB_SHA_OVERRIDE', '') if env_var('GITHUB_SHA_OVERRIDE', '') else env_var('GITHUB_SHA') }}_tap_kustomer

seeds:
  +schema: tap_kustomer
