name: CI Integration Tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DBT_PROFILES_DIR: ${{ github.workspace }}/integration_tests/
  GITHUB_SHA_OVERRIDE: ${{ github.event.pull_request.head.sha }} # We need the commit hash of the pull request branch's head, the GITHUB_SHA env var is always the base branch in a pull_request_target trigger
  # These are configured in GitHub secrets
  DBT_ENV_SECRET_POSTGRES_DATABASE_NAME: ${{ secrets.POSTGRES_DATABASE_NAME }}
  DBT_ENV_SECRET_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  DBT_ENV_SECRET_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}

jobs:
  integration-postgres:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/integration_tests/

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DATABASE_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Check out the code of the PR

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.10.x"
          architecture: "x64"

      - name: Install dbt
        run: python3 -m pip install dbt-postgres==1.4.5

      - name: Test dbt database connection
        run: dbt debug

      - name: Install dbt packages
        run: dbt deps

      - name: Seed dbt test data
        run: dbt seed --full-refresh

      - name: Run dbt models
        run: |
          dbt run -s stg_kustomer__customers --full-refresh

      - name: Test dbt models
        run: |
          dbt test
